# Convert cleaned, imputed data generated by titanic_data_process.R into a data.table using the xgb.DMatrix() function
#
# Run a regularized gradient-boosted decision tree ensemble with random search for parameter tuning. See reference.
#


### Clear memory
rm(list=ls())

### Load packages
library(caret)
library(mlr)
library(xgboost)

### Define root directory
root <- "C:\\Users\\kenri\\OneDrive\\titanic_survival_pred"


# Load in training and test sets
train <- readRDS(paste0(root, "\\Data\\train.rds"))
test <- readRDS(paste0(root, "\\Data\\test.rds"))

# Define labels for training and test sets
train_labels <- train$survived

test_labels <- read.csv(paste0(root, "\\Raw Data\\test_labels.csv"))
test_labels <- test_labels$survived  # To be removed later for submission. I am using these values to 
                                     # validate my model's accuracy with that reported by Kaggle.
                                     # These are the actual values that I wish to duplicate!
  
# Convert to one-hot encoding using model.matrix()
#options(na.action = 'na.pass')

train <- model.matrix(~.+0, train[, colnames(train) != "survived"]) 
test <- model.matrix(~.+0, test)
  
#options(na.action = 'na.omit')
  

### Convert matrix to xgb.DMatrix object
train <- xgb.DMatrix(train, label = train_labels)
test <- xgb.DMatrix(test, label = test_labels)




params <- list(booster = "gbtree", objective = "multi:softmax", num_class=2,  
               eta=0.05, gamma=0, max_depth=30, min_child_weight=1, subsample=0.5, colsample_bytree=0.5)



xgbcv <- xgb.cv(params = params, data = train, nrounds = 100, nfold = 10, showsd = T, 
                stratified = T, print_every_n = 10, early_stopping_rounds = 20, maximize = F)

best_nrounds = xgbcv[8]$best_iteration
  
  

xgb1 <- xgb.train (params = params, data = train, nrounds = best_nrounds, 
                   watchlist = list(val = test,train = train), print_every_n = 10, 
                   early_stopping_rounds = 20, maximize = F , eval_metric = "merror")


xgbpred <- predict(xgb1, test)
#xgbpred <- ifelse(xgbpred > 0.5, 1, 0)



confusionMatrix(as.factor(xgbpred), as.factor(test_labels))









  